"""
state.py

Defines the shared State TypedDict used across all agents in the multi-agent system.
This state is passed through the LangGraph graph and mutated by each node.
"""

from typing import Any, Optional
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


class UserInfo(TypedDict, total=False):
    """Structured information about the user extracted during conversation."""
    name: str
    email: str
    company: str
    role: str


class State(MessagesState):
    """
    Shared state object that flows through the entire agent graph.

    Fields:
        messages:       Conversation history (inherited from MessagesState).
        intent:         Classified intent of the user's request (e.g. 'support', 'freelance').
        user_info:      Structured user metadata extracted from conversation.
        proposal_draft: Work-in-progress proposal text generated by the freelance agent.
    """
    intent: Optional[str]
    user_info: Optional[UserInfo]
    proposal_draft: Optional[str]